### ISSUE TITLE
What to do when push notifications are not enabled

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe-ios#167]
At the moment when an user doesn't enable the push notifications the function to register the probe is never called, as the token is null.
Should we register anyway the probe maybe with empty token? Or it's useless?
What about in the 2.0 version?

**Comment by hellais** [comment]
This is an interesting question. Currently when the probe to be registered is on Android or iOS, the token field is a requirement and you will not be able to register a probe if they don't have a token.

I do think, however, that there is some value to have the client register even if they don't have a push notification token. I am thinking that this can be useful because:

* It allows us to know the distribution of probes around the world
* It allows us to know how many of these probes don't have the push notification token enabled
* We could implement logic that when somebody requests a URL list from proteus, we give them a URL list depending on the history of their probe (for manually triggered tests)

I am going to create a ticket on proteus as well to keep track of this and I would say we should aim to have this be the logic for 2.0.

**Comment by hellais** [comment]
xref: https://github.com/TheTorProject/proteus/issues/41

**Comment by lorenzoPrimi** [comment]
@hellais at the moment if the token is null, the client is never registered.
This means for many iOS user to be never registered
Would be better to register them with empty token?

**Comment by hellais** [comment]
> Would be better to register them with empty token?

I think that would be better, but I need to first fix ooni/orchestra#41.

**Comment by lorenzoPrimi** [comment]
So for now keeping the code as is without registering them.

**Comment by hellais** [comment]
> So for now keeping the code as is without registering them.

I will update this ticket if I get around to doing it, I suppose it's not a big change, but I think it's important we fix https://github.com/ooni/probe-ios/issues/180 first.

**Comment by lorenzoPrimi** [comment]
@hellais I guess this and https://github.com/ooni/orchestra/issues/41 are kinda urgent as at the moment we don't ask for push notifications on iOS meaning we have no probes registered

**Comment by lorenzoPrimi** [comment]
Wait https://github.com/ooni/orchestra/pull/60 to be merged.
We need a way to register probe without enabling the push notifications, as at the moment only when we get the token we register them

**Comment by lorenzoPrimi** [comment]
@hellais when the user hasn't enable the push notification should I send empty string or omit that parameter?

**Comment by hellais** [comment]
> @hellais when the user hasn't enable the push notification should I send empty string or omit that parameter?

It's equivalent. I would suggest you send an empty string.
