### ISSUE TITLE
Construct URL using NSURLComponents

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe-ios#294]
As highlighted here by @bassosimone https://github.com/ooni/probe-ios/pull/293
`I would suggest here to see whether there is a Cocoa facility for building URLs in a robust way. I am especially concerned with proper escaping. I bet there is a safe Cocoa way to construct a query string and then attaching it to a URL in a way that escaping is on the library rather than on us.`

This is an alternative way to build an URL : https://content.pivotal.io/blog/building-urls-with-nsurlqueryitems-and-nsurlcomponents

Although I never seen this pattern in any app, and I believe increase only complexity in building an URL that should be a simple string `NSString *path = [NSString stringWithFormat:@"https://orchestrate.ooni.io/api/v1/test-list/urls?country_code=%@", cc];`

What can be done if the concern is the encoding is to encode the URL in this way:
`NSString* url = [NSString *path = [NSString stringWithFormat:@"https://orchestrate.ooni.io/api/v1/test-list/urls?country_code=%@", cc]] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];`

Open for discussion

**Comment by bassosimone** [comment]
@lorenzoPrimi I believe it's pretty straightforward to choose NSURLComponent and I'll try below why I have a strong preference for us using it as opposed to using plain strings.

> [...] This is an alternative way to build an URL [...]

No, this is not an "alternative way". This should be the number one choice when trying to apply software engineering principles to an iOS app. Let me explain my reasoning below.

Building a URL using the platform provided facilities as opposed to assembling it as a string (and possibly applying hacks to quote the whole string) is more robust and more forward looking.

The "complexity" that you're complaining of is actually delegating to the platform to properly assemble the URL and make sure it emits a correct URL. This means that the responsibility of guaranteeing that the URL will be okay, with proper unit and integration testing, shifts from you to the platform. This means that you don't need to write the tests yourself and make sure your homebrew method works okay. And, if you think at this, that's actually less and not more work of you _now_. But there's more.

I really like this concept [reiterated by Russ Cox in the 2018 GopherConSG kenynote](https://youtu.be/F8nrpe0XWRg?t=199) that "software engineering is what happens to programming when you add time and other programmers". To relate this concept to our current discussion, here we're not trying to hastily write a piece of ObjectiveC that should just work tomorrow, but we're trying to learn and promote best practices and make sure the code we write today is modular, reusable, well tested, and still understandable and manageable in the future. To this end, we need to make a little more effort in writing it, but this effort is eventually paid off by our reduced effort in the future.

Code can and will change, take this for granted. Code will be copied and adapted. By using the most robust pattern, we're doing a favour to our future selves, in that we'll be able to apply changes more freely. By not using such good practices, we're increasing the likelihood that we'll need to rewrite entire chunks of the apps when the requirements change, because we have no confidence that they work as intended and because it has become a mess and we don't have time, etc.

> Although I never seen this pattern in any app, [...]

It does not surprise me that a possibly-closed-source app written by a single programmer either for fun or for a specific client, as a one-off-ish exercise, does not use more robust patterns. This is fine in that context, but it's also worth noting that here we're playing a different game, aren't we?

> [...] I believe increase only complexity in building an URL that should be a simple string

As I said above, this solution works best when you're a solo programmer and you anticipate that there will be little or no breaking changes in that code for a long time. Or when you're charging a client for such changes, so that a future revamp of the code could lead you to invoice more. We're not in this case here, also because the code is open source, and more importantly because "engineering".

What's more, as I also said above, you should consider considering in your definition of simplicity also the amount of regression tests you need to write to guarantee the code works as intended(TM).

> [...] if the concern is the encoding is to encode the URL in this way

Please, don't. The concern is engineering. The concern is minimising the number of hacks and home made solutions assembled to solve the problem. Adding this kind of escaping seems quite not the right thing to do here. Can you apply percent encoding to all components of a URL, or is percent encoding only to be applied in the path? Think of the poor code reviewer or your future self re-reading the code and having perhaps to read again the RFC to understand whether that hack is correct. Think of your poor future self (or my future self, or whoever) having to maintain a tests suite made significantly larger by tests specifically designed to make sure the hack works as intended. Now, instead, think of just using the functionality made available by the platform and trusing it to be correct [*]. Doesn't it sound a little bit less of burden to use this solution instead? Don't you feel relieve if you think about that?

- - -

[*] Blindly trusting the platform is not a good thing to do, actually. So, there may be reasons not to trust Apple here, because for example it's known that NSURLComponent is broken. This is a different set of objections, and I am available to have a conversation on that subject, which however is a different one.
